apiVersion: v1
kind: ConfigMap
metadata:
  name: postiz-redis-configuration
  labels:
    app.kubernetes.io/name: postiz-redis
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: postiz
data:
  redis.conf: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
  master.conf: |-
    dir /data
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
