apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: postiz-redis
  labels:
    app.kubernetes.io/name: postiz-redis
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: postiz
