apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postiz-redis
  labels:
    app.kubernetes.io/name: postiz-redis
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: postiz
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: postiz-redis
      app.kubernetes.io/component: redis
  serviceName: postiz-redis-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postiz-redis
        app.kubernetes.io/instance: postiz
        app.kubernetes.io/component: redis
        app.kubernetes.io/part-of: postiz
    spec:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: Always
      serviceAccountName: postiz-redis
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      containers:
        - name: redis
          image: redis:8.2-alpine
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
            seccompProfile:
              type: RuntimeDefault
          command:
            - redis-server
          args:
            - /etc/redis/redis.conf
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postiz-redis-secret
                  key: redis-password
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping | grep -q PONG
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping | grep -q PONG
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 192Mi
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: config
              mountPath: /etc/redis
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: postiz-redis-configuration
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
