apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  image: "ghcr.io/pikol-app/identity:1.0.2"
  imagePullSecrets:
    - name: "pikol-pull-secret"
  db:
    vendor: postgres
    host: postgres-cluster-rw
    usernameSecret:
      name: keycloak-db-credentials
      key: username
    passwordSecret:
      name: keycloak-db-credentials
      key: password
    database: keycloak-db
  hostname:
    hostname: auth.piko.app
  http:
    httpEnabled: false
    tlsSecret: keycloak-tls
  proxy:
    headers: xforwarded
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  additionalOptions:
    - name: db-pool-initial-size
      value: "5"
    - name: db-pool-max-size
      value: "20"
    - name: db-pool-min-size
      value: "5"
    - name: log-level
      value: "INFO"
  unsupported:
    podTemplate:
      spec:
        containers:
          - name: keycloak
            env:
              - name: KC_HTTP_ENABLED
                value: "false"
              - name: KC_PROXY_HEADERS
                value: "xforwarded"
              - name: QUARKUS_HTTP_HTTP2
                value: "false"
              - name: KC_HOSTNAME
                value: "https://auth.pikol.app"
              - name: JAVA_OPTS_APPEND
                value: >-
                  -Xms1024m
                  -Xmx1536m
                  -XX:MetaspaceSize=128M
                  -XX:MaxMetaspaceSize=384m
                  -XX:+UseG1GC
                  -XX:MaxGCPauseMillis=100
                  -XX:+ParallelRefProcEnabled
                  -XX:+DisableExplicitGC
                  -XX:+HeapDumpOnOutOfMemoryError
                  -XX:HeapDumpPath=/tmp/heap-dump.hprof
                  -Djava.net.preferIPv4Stack=true
                  -Djboss.modules.system.pkgs=org.jboss.byteman
              - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
                value: "false"
              - name: KC_HTTP_POOL_MAX_THREADS
                value: "50"
              - name: KC_CACHE
                value: "ispn"
              - name: KC_CACHE_STACK
                value: "kubernetes"
              - name: KC_BOOTSTRAP_ADMIN_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: keycloak-admin-credentials
                    key: username
              - name: KC_BOOTSTRAP_ADMIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: keycloak-admin-credentials
                    key: password
