apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak-operator
  endpoints:
    - port: management
      path: /metrics
      scheme: http
      interval: 30s
