apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  endpoints:
    - port: management
      path: /metrics
      scheme: https
      interval: 30s
      tlsConfig:
        insecureSkipVerify: true 
