apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak
  namespace: evtzp-web
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  podMetricsEndpoints:
    - port: management
      path: /metrics
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
