apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-dynamicconfig
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/component: temporal
    app.kubernetes.io/part-of: postiz
data:
  development-sql.yaml: |
    limit.maxIDLength:
      - value: 255
        constraints: {}
    system.forceSearchAttributesCacheRefreshOnRead:
      - value: true
        constraints: {}
