apiVersion: v1
kind: ConfigMap
metadata:
  name: postiz-config
  labels:
    app.kubernetes.io/name: postiz
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: postiz
data:
  BACKEND_INTERNAL_URL: "http://localhost:3000"
  FRONTEND_URL: "https://xxx"
  MAIN_URL: "https://xxx"
  NEXT_PUBLIC_BACKEND_URL: "https://xxx/api"
  IS_GENERAL: "true"
  NX_ADD_PLUGINS: "false"
  STORAGE_PROVIDER: "local"
  UPLOAD_DIRECTORY: "/uploads"
  NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
  NEXT_PUBLIC_UPLOAD_STATIC_DIRECTORY: ""
  DISABLE_REGISTRATION: "false"
  RUN_CRON: "true"
  API_LIMIT: "30"
  TEMPORAL_ADDRESS: "temporal:7233"
