apiVersion: v1
kind: ServiceAccount
metadata:
  name: postiz
  labels:
    app.kubernetes.io/name: postiz
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: postiz
