apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: exporter
spec:
  selector:
    matchLabels:
      app: exporter
  podMetricsEndpoints:
    - port: web
      path: /metrics
      interval: 30s
