apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exporter
spec:
  selector:
    matchLabels:
      app: exporter
  endpoints:
    - port: web
      path: /metrics
      interval: 30s
