apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: static
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: static
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: static
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 500m
          memory: 200Mi
